/**
 * Error Code Enums
 *
 * Comprehensive enum of ALL error codes.
 * NO MAGIC STRINGS - use these enums everywhere!
 */

/**
 * Universal Error Codes
 *
 * Protocol-agnostic error codes that work across all transports.
 */
export enum ErrorCode {
  // Network errors
  NETWORK_ERROR = "NETWORK_ERROR",
  CONNECTION_REFUSED = "CONNECTION_REFUSED",
  DNS_ERROR = "DNS_ERROR",

  // Timeout errors
  TIMEOUT = "TIMEOUT",
  CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT",
  READ_TIMEOUT = "READ_TIMEOUT",
  DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED",

  // Cancellation
  ABORTED = "ABORTED",

  // Protocol/parsing errors
  PARSE_ERROR = "PARSE_ERROR",
  SERIALIZE_ERROR = "SERIALIZE_ERROR",
  INVALID_RESPONSE = "INVALID_RESPONSE",
  PROTOCOL_ERROR = "PROTOCOL_ERROR",

  // Client errors (4xx equivalent)
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  NOT_ACCEPTABLE = "NOT_ACCEPTABLE",
  PROXY_AUTHENTICATION_REQUIRED = "PROXY_AUTHENTICATION_REQUIRED",
  CONFLICT = "CONFLICT",
  GONE = "GONE",
  LENGTH_REQUIRED = "LENGTH_REQUIRED",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  URI_TOO_LONG = "URI_TOO_LONG",
  UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE",
  RANGE_NOT_SATISFIABLE = "RANGE_NOT_SATISFIABLE",
  EXPECTATION_FAILED = "EXPECTATION_FAILED",
  IM_A_TEAPOT = "IM_A_TEAPOT",
  MISDIRECTED_REQUEST = "MISDIRECTED_REQUEST",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",
  LOCKED = "LOCKED",
  FAILED_DEPENDENCY = "FAILED_DEPENDENCY",
  TOO_EARLY = "TOO_EARLY",
  UPGRADE_REQUIRED = "UPGRADE_REQUIRED",
  PRECONDITION_REQUIRED = "PRECONDITION_REQUIRED",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  REQUEST_HEADER_FIELDS_TOO_LARGE = "REQUEST_HEADER_FIELDS_TOO_LARGE",
  UNAVAILABLE_FOR_LEGAL_REASONS = "UNAVAILABLE_FOR_LEGAL_REASONS",
  CLIENT_CLOSED_REQUEST = "CLIENT_CLOSED_REQUEST",

  // Server errors (5xx equivalent)
  INTERNAL_ERROR = "INTERNAL_ERROR",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  BAD_GATEWAY = "BAD_GATEWAY",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT",
  HTTP_VERSION_NOT_SUPPORTED = "HTTP_VERSION_NOT_SUPPORTED",
  VARIANT_ALSO_NEGOTIATES = "VARIANT_ALSO_NEGOTIATES",
  INSUFFICIENT_STORAGE = "INSUFFICIENT_STORAGE",
  LOOP_DETECTED = "LOOP_DETECTED",
  NOT_EXTENDED = "NOT_EXTENDED",
  NETWORK_AUTHENTICATION_REQUIRED = "NETWORK_AUTHENTICATION_REQUIRED",
  HTTP_NETWORK_CONNECT_TIMEOUT = "HTTP_NETWORK_CONNECT_TIMEOUT",

  // Configuration errors
  INVALID_CONFIG = "INVALID_CONFIG",
  INVALID_URL = "INVALID_URL",
  INVALID_METHOD = "INVALID_METHOD",

  // HTTP-specific
  HTTP_ERROR = "HTTP_ERROR",

  // Unknown
  UNKNOWN = "UNKNOWN",
}
